# Generated by Django 4.2.13 on 2026-03-13 05:21

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("instagram", "Instagram"),
                        ],
                        max_length=15,
                    ),
                ),
                ("platform_user_id", models.CharField(max_length=100)),
                ("platform_username", models.CharField(max_length=100)),
                ("access_token", encrypted_model_fields.fields.EncryptedTextField()),
                (
                    "refresh_token",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-connected_at"],
                "unique_together": {("user", "platform")},
            },
        ),
    ]
