# Generated by Django 4.2.13 on 2026-03-13 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("credits", models.IntegerField(default=5)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("starter", "Starter"),
                            ("basic", "Basico"),
                            ("pro", "Profesional"),
                            ("ultimate", "Ultimate"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("plan_expires_at", models.DateTimeField(blank=True, null=True)),
                ("referral_code", models.CharField(max_length=12, unique=True)),
                ("total_videos_generated", models.IntegerField(default=0)),
                ("avatar_url", models.URLField(blank=True, null=True)),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="users.userprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "concept",
                    models.CharField(
                        choices=[
                            ("welcome_bonus", "Bono de Bienvenida"),
                            ("plan_purchase", "Compra de Plan"),
                            ("video_generated", "Video Generado"),
                            ("video_failed_refund", "Reembolso por Fallo"),
                            ("referral_bonus", "Bono de Referido"),
                            ("admin_adjustment", "Ajuste Administrativo"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transactions",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
