# Generated by Django 4.2.13 on 2026-03-13 05:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("script", models.TextField(max_length=2000)),
                (
                    "video_type",
                    models.CharField(
                        choices=[
                            ("prompt_to_video", "Prompt to Video"),
                            ("sora2", "Sora 2"),
                            ("ai_asmr", "AI ASMR (Veo3)"),
                        ],
                        default="prompt_to_video",
                        max_length=20,
                    ),
                ),
                ("style", models.CharField(default="anime", max_length=50)),
                ("voice_id", models.CharField(max_length=100)),
                ("voice_name", models.CharField(blank=True, max_length=100)),
                ("music_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("9:16", "9:16 Vertical"),
                            ("16:9", "16:9 Horizontal"),
                            ("1:1", "1:1 Cuadrado"),
                        ],
                        default="9:16",
                        max_length=5,
                    ),
                ),
                ("clips_count", models.IntegerField(default=3)),
                ("clip_duration", models.IntegerField(default=4)),
                ("credits_used", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("generating_images", "Generando Imagenes"),
                            ("generating_audio", "Generando Audio"),
                            ("rendering", "Renderizando"),
                            ("uploading", "Subiendo"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("video_url", models.URLField(blank=True, null=True)),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("resolution", models.CharField(default="1080p", max_length=10)),
                ("file_size_mb", models.FloatField(blank=True, null=True)),
                (
                    "n8n_execution_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("published_to_tiktok", models.BooleanField(default=False)),
                ("published_to_youtube", models.BooleanField(default=False)),
                ("published_to_instagram", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoScene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("prompt", models.TextField(blank=True)),
                ("narration_text", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(default=4)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenes",
                        to="videos.videogeneration",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
