# Generated by Django 4.2.13 on 2026-03-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("music_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("epic", "Epico"),
                            ("terror", "Terror / Misterio"),
                            ("happy", "Positivo / Alegre"),
                            ("lofi", "Lofi / Relajante"),
                            ("drama", "Drama"),
                        ],
                        max_length=20,
                    ),
                ),
                ("preview_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Music tracks",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("emoji", models.CharField(max_length=10)),
                ("is_new", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Voice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voice_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                ("tags", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", "Masculino"), ("f", "Femenino")], max_length=1
                    ),
                ),
                ("preview_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
